version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11.14
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: yarn prettier:check
      - run: yarn test
      - run: yarn build
workflows:
  version: 2
  build:
    jobs:
      - build
